### ISSUE TITLE
What kind of type environment are there?

### ISSUE THREAD

**Issue by masaya611** [YetAnotherPolicy/RMIX#1]
Hello.

Does this Github repositiry RMIX not have "Multi-Agent Cliff Navigation" environment?

**Comment by YetAnotherPolicy** [comment]
> Hello.
> 
> Does this Github repositiry RMIX not have "Multi-Agent Cliff Navigation" environment?

Hi, thanks for your interest. Currently Multi-Agent Cliff Navigation is not in this repo. I am planning put it in this repo.
